const actionTypes={
    bookaction:{
        GET_BOOKS_START:"GET_BOOKS_START",
        GET_BOOKS_SUCCESS:"GET_BOOKS_SUCCESS",
        GET_BOOKS_FAİL:"GET_BOOKS_FAİL",
        DELETE_BOOK_START:"DELETE_BOOK_START",
        DELETE_BOOK_SUCCESS:"DELETE_BOOK_SUCCESS",
        DELETE_BOOK_FAİL:"DELETE_BOOK_FAİL"

    },

    categoryAction:{
        GET_CATEGORIES_START:"GET_CATEGORIES_START",
        GET_CATEGORIES_SUCCESS:"GET_CATEGORIES_SUCCESS",
        GET_CATEGORIES_FAİL:"GET_CATEGORIES_FAİL"

    }
}

export default actionTypes